### ISSUE TITLE
React support?

### ISSUE THREAD

**Issue by demiters** [PhilippSpo/momentum-flow-router#13]
Is there any possibility of supporting React in the future? Or any hack that makes it work?

**Comment by PhilippSpo** [comment]
Since this package is using `momentum`, which at the moment (and most likely also in the future) only supports Blaze, there is no way of supporting React.
If you are using `react-router` there is an example in their repo on how to do route transition animations [here](https://github.com/reactjs/react-router/blob/master/examples/animations/app.js).
