### ISSUE TITLE
Breaking app

### ISSUE THREAD

**Issue by dapearce** [PhilippSpo/momentum-flow-router#2]
Hi Philipp, your demo looks great. I just ported to Flow Router today and love it so far. Unfortunately, when I add this package it immediately breaks my app, before I even try to implement anything. Any idea what I might be missing?

![screen shot 2015-05-26 at 3 22 22 pm](https://cloud.githubusercontent.com/assets/1824987/7821293/db61df10-03bb-11e5-8c04-405baa6f6176.png)

**Comment by PhilippSpo** [comment]
This error was due to the Flow-Router update to [version](https://github.com/meteorhacks/flow-router/commit/bf88e85efb6f820cb24a883587c5b8882ceac109) 1.9.0, which changed the way you can get the route name.
Should be fixed now. Just update the momentum-flow-router package to 0.0.3
36411deca96e85fcaea7c8e4318991b24332408c

**Comment by PhilippSpo** [comment]
There is still some weirdness happening when changing routes.. seems to apply the wrong transition sometimes.. i'll look into it real quick

**Comment by PhilippSpo** [comment]
Alright back to normal again :)
Now the package is using Flow-Router 1.9.0 and working as usual.
The demo is also updated and deployed.
Please update to version 0.0.4 of `momentum-flow-router`

**Comment by dapearce** [comment]
Thanks for the quick response. I updated and it fixed the errors. Unfortunately I'm having some trouble implementing in my app, but I'm guessing it's just confusion on my part. Is it possible to use this between different flow layouts? Or does it have to be the same layout?

**Comment by PhilippSpo** [comment]
Haven't tried different layouts yet. But that should not be a problem..

**Comment by PhilippSpo** [comment]
Yes switching layouts is a problem, since the html nodes that change are not wrapped inside the momentum helper anymore..

**Comment by PhilippSpo** [comment]
So I did some research and it turns out, that momentum uses Meteors [_uihooks](https://github.com/meteor/meteor/blob/master/History.md#blaze-2) in order to perform animations once a DOM node gets inserted. These uihooks only work for nodes, that get manipulated by Blaze, not nodes that you insert manually using jQuery or normal javascript. This is problematic since FlowLayout uses jQuery to render a new Layout to the DOM. And this is probably what would need to change in order to get this working...

**Comment by PhilippSpo** [comment]
worked on the flow-layout package and got it working:
http://flow-layout-transitions.meteor.com/
Made a [Pull Request](https://github.com/meteorhacks/flow-layout/pull/19) on the FlowLayout for this.. If that gets merged we'll have layout transitions :)

**Comment by arunoda** [comment]
Hey, would you mind sharing the code for `http://flow-layout-transitions.meteor.com/`. I'd like to support it. But somehow I don't like the way you done it in the PR.

**Comment by PhilippSpo** [comment]
The Code is here: https://github.com/PhilippSpo/momentum-flow-router-demo/tree/flow-layout-transitions
I would be glad to reason about and improve the code :)
